version: '3.8'
services:
  web:
    build: .  
    image: mary747/presentation-api-v1:latest 
    
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8000:8000"
   
    environment:
      - REDIS_SERVER=redis-cache
      - REDIS_PORT=6379
      
    depends_on:
      - redis-cache
    command:  "poetry run uvicorn main:app --reload "
      
  

  redis-cache:
    image: redis
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

volumes:
 

  cache:
    driver: local
