version: '3.8'
services:
  web:
    build: .  
    image: mary747/presentation-api-v1:latest 
    
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
   
    command:  "uvicorn main:app --host 0.0.0.0 --port 8000 --ssl-keyfile /etc/uvicorn/ssl/selfsigned.key --ssl-certfile /etc/uvicorn/ssl/selfsigned.crt --log-level debug"
      
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}  
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME}  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
